//
//  CopyableLabel.swift
//  msnemykinPW2
//
//  Created by Михаил Немыкин on 29.10.2024.
//

import UIKit

class CopyableLabel: UIView {
    // MARK: - Constants
    enum Constants {
        static let textFontSize: CGFloat = 16
        static let textColor: UIColor = .white
        static let textAlignment: NSTextAlignment = .center
        
        static let alertTitle: String = "Цвет скопирован!"
        static let alertDuration: TimeInterval = 1
    }
    // MARK: - Fields
    let label: UILabel = {
        let label = UILabel()
        
        label.font = .systemFont(ofSize: Constants.textFontSize)
        label.textColor = Constants.textColor
        label.textAlignment = Constants.textAlignment
        
        return label
    }()
    // MARK: - Lifecycle methods
    init() {
        super.init(frame: .zero)
        ConfigureUI()
        ConfigureGesture()
    }
    
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    // MARK: - Private Methods
    private func ConfigureUI() {
        addSubview(label)
        label.pinCenter(to: self)
    }
    
    private func ConfigureGesture() {
        isUserInteractionEnabled = true
        let longPressGesture = UITapGestureRecognizer(target: self, action: #selector(copyText))
        addGestureRecognizer(longPressGesture)
    }
        
    private func showCopyConfirmation() { // generated by chatGPT :)
        let alert = UIAlertController(title: nil, message: Constants.alertTitle, preferredStyle: .alert)
        
        if let scene = UIApplication.shared.connectedScenes.first as? UIWindowScene,
           let window = scene.windows.first(where: { $0.isKeyWindow }),
           let rootViewController = window.rootViewController{
            rootViewController.present(alert, animated: true)
            DispatchQueue.main.asyncAfter(deadline: .now() + Constants.alertDuration) {
                alert.dismiss(animated: true)
            }
        }
    }
    // MARK: - Objc Methods
    @objc private func copyText() {
        UIPasteboard.general.string = label.text
        showCopyConfirmation()
    }
    
}

